# Copyright © 2015 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
---
- name: daemon reload
  command: systemctl daemon-reload

- name: restart flannel
  service:
    name: flannel
    state: restarted
    enabled: yes

- name: restart docker
  service:
    name: docker
    state: restarted
    enabled: yes

- name: restart kube-proxy
  service:
    name: kube-proxy
    state: restarted
    enabled: yes

- name: restart kubelet
  service:
   name: kubelet
   state: restarted
   enabled: yes
